<?php

return array(
	'MASTER_DATA_VERSION' => 1,
	'CRYSTAL_DEFAULT' => 0,
	'CRYSTAL_FREE_DEFAULT' => 10,
	'FRIEND_COIN_DEFAULT' => 0,
	'TUTORIAL_START' => 0,
	'ITEM_TYPE_CRYSTAL' => 1,
	'ITEM_TYPE_CRYSTAL_FREE' => 2,
	'ITEM_TYPE_FRIEND_COIN' => 3,
	'TUTORIAL_START' => 0,
	'TUTORIAL_QUEST' => 10,
	'TUTORIAL_GACHA' => 20,
	'TUTORIAL_FINISH' => 999,
	'QUEST_START' => 1,
	'QUEST_RETIRT' => 2,
	'QUEST_CLEAR' => 3,
	'GACHA_COST_TYPE_CRYSTAL' => 1,
	'GACHA_COST_TYPE_CRYSTAL_FREE' => 2,
	'GACHA_COST_TYPE_FRIEND_COIN' => 3,
);